// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.27.3
// source: protos/user/user.proto

/* eslint-disable */

export const protobufPackage = "user";

export const Gender = { MALE: "MALE", FEMALE: "FEMALE", OTHER: "OTHER", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type Gender = typeof Gender[keyof typeof Gender];

export namespace Gender {
  export type MALE = typeof Gender.MALE;
  export type FEMALE = typeof Gender.FEMALE;
  export type OTHER = typeof Gender.OTHER;
  export type UNRECOGNIZED = typeof Gender.UNRECOGNIZED;
}

export const WeightGoal = {
  LOSE_WEIGHT: "LOSE_WEIGHT",
  MAINTAIN_WEIGHT: "MAINTAIN_WEIGHT",
  GAIN_WEIGHT: "GAIN_WEIGHT",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type WeightGoal = typeof WeightGoal[keyof typeof WeightGoal];

export namespace WeightGoal {
  export type LOSE_WEIGHT = typeof WeightGoal.LOSE_WEIGHT;
  export type MAINTAIN_WEIGHT = typeof WeightGoal.MAINTAIN_WEIGHT;
  export type GAIN_WEIGHT = typeof WeightGoal.GAIN_WEIGHT;
  export type UNRECOGNIZED = typeof WeightGoal.UNRECOGNIZED;
}

export const ActivityLevel = {
  SEDENTARY: "SEDENTARY",
  LIGHTLY_ACTIVE: "LIGHTLY_ACTIVE",
  MODERATELY_ACTIVE: "MODERATELY_ACTIVE",
  VERY_ACTIVE: "VERY_ACTIVE",
  EXTREMELY_ACTIVE: "EXTREMELY_ACTIVE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type ActivityLevel = typeof ActivityLevel[keyof typeof ActivityLevel];

export namespace ActivityLevel {
  export type SEDENTARY = typeof ActivityLevel.SEDENTARY;
  export type LIGHTLY_ACTIVE = typeof ActivityLevel.LIGHTLY_ACTIVE;
  export type MODERATELY_ACTIVE = typeof ActivityLevel.MODERATELY_ACTIVE;
  export type VERY_ACTIVE = typeof ActivityLevel.VERY_ACTIVE;
  export type EXTREMELY_ACTIVE = typeof ActivityLevel.EXTREMELY_ACTIVE;
  export type UNRECOGNIZED = typeof ActivityLevel.UNRECOGNIZED;
}

export const UnitSystem = { METRIC: "METRIC", IMPERIAL: "IMPERIAL", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type UnitSystem = typeof UnitSystem[keyof typeof UnitSystem];

export namespace UnitSystem {
  export type METRIC = typeof UnitSystem.METRIC;
  export type IMPERIAL = typeof UnitSystem.IMPERIAL;
  export type UNRECOGNIZED = typeof UnitSystem.UNRECOGNIZED;
}

export interface UserProfile {
  height?: number | undefined;
  weight?: number | undefined;
  targetWeight?: number | undefined;
  gender?:
    | Gender
    | undefined;
  /** ISO 8601 format (e.g., "2024-01-15T10:30:00.000Z") */
  dateOfBirth?: string | undefined;
  weightGoal?: WeightGoal | undefined;
  activityLevel?: ActivityLevel | undefined;
  heightUnit?: UnitSystem | undefined;
  weightUnit?: UnitSystem | undefined;
  dailyCalorieGoal?: number | undefined;
}
