// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.27.3
// source: protos/wear/wear_protocol.proto

/* eslint-disable */
import type { FavoriteMeal, LoggedMeal } from "../app/meal";
import type { MealDetectionResponse } from "../calorify/meal_detection";
import type { UserProfile } from "../user/user";

export const protobufPackage = "wear";

/**
 * Version 1 is the path + JSON protocol retained for one compatibility cycle.
 * Version 2 is the first generated, binary envelope protocol.
 */
export const WearProtocolVersion = {
  WEAR_PROTOCOL_VERSION_UNSPECIFIED: "WEAR_PROTOCOL_VERSION_UNSPECIFIED",
  WEAR_PROTOCOL_VERSION_LEGACY_V1: "WEAR_PROTOCOL_VERSION_LEGACY_V1",
  WEAR_PROTOCOL_VERSION_V2: "WEAR_PROTOCOL_VERSION_V2",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type WearProtocolVersion = typeof WearProtocolVersion[keyof typeof WearProtocolVersion];

export namespace WearProtocolVersion {
  export type WEAR_PROTOCOL_VERSION_UNSPECIFIED = typeof WearProtocolVersion.WEAR_PROTOCOL_VERSION_UNSPECIFIED;
  export type WEAR_PROTOCOL_VERSION_LEGACY_V1 = typeof WearProtocolVersion.WEAR_PROTOCOL_VERSION_LEGACY_V1;
  export type WEAR_PROTOCOL_VERSION_V2 = typeof WearProtocolVersion.WEAR_PROTOCOL_VERSION_V2;
  export type UNRECOGNIZED = typeof WearProtocolVersion.UNRECOGNIZED;
}

export const WearOperation = {
  WEAR_OPERATION_UNSPECIFIED: "WEAR_OPERATION_UNSPECIFIED",
  WEAR_OPERATION_MEAL_LOG: "WEAR_OPERATION_MEAL_LOG",
  WEAR_OPERATION_MEAL_DELETE: "WEAR_OPERATION_MEAL_DELETE",
  WEAR_OPERATION_TODAY_MEALS: "WEAR_OPERATION_TODAY_MEALS",
  WEAR_OPERATION_CALORIE_GOAL: "WEAR_OPERATION_CALORIE_GOAL",
  WEAR_OPERATION_USER_PROFILE: "WEAR_OPERATION_USER_PROFILE",
  WEAR_OPERATION_FAVORITES: "WEAR_OPERATION_FAVORITES",
  WEAR_OPERATION_AUTH_SESSION: "WEAR_OPERATION_AUTH_SESSION",
  WEAR_OPERATION_DETECT_TEXT: "WEAR_OPERATION_DETECT_TEXT",
  WEAR_OPERATION_DATA_CHANGED: "WEAR_OPERATION_DATA_CHANGED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type WearOperation = typeof WearOperation[keyof typeof WearOperation];

export namespace WearOperation {
  export type WEAR_OPERATION_UNSPECIFIED = typeof WearOperation.WEAR_OPERATION_UNSPECIFIED;
  export type WEAR_OPERATION_MEAL_LOG = typeof WearOperation.WEAR_OPERATION_MEAL_LOG;
  export type WEAR_OPERATION_MEAL_DELETE = typeof WearOperation.WEAR_OPERATION_MEAL_DELETE;
  export type WEAR_OPERATION_TODAY_MEALS = typeof WearOperation.WEAR_OPERATION_TODAY_MEALS;
  export type WEAR_OPERATION_CALORIE_GOAL = typeof WearOperation.WEAR_OPERATION_CALORIE_GOAL;
  export type WEAR_OPERATION_USER_PROFILE = typeof WearOperation.WEAR_OPERATION_USER_PROFILE;
  export type WEAR_OPERATION_FAVORITES = typeof WearOperation.WEAR_OPERATION_FAVORITES;
  export type WEAR_OPERATION_AUTH_SESSION = typeof WearOperation.WEAR_OPERATION_AUTH_SESSION;
  export type WEAR_OPERATION_DETECT_TEXT = typeof WearOperation.WEAR_OPERATION_DETECT_TEXT;
  export type WEAR_OPERATION_DATA_CHANGED = typeof WearOperation.WEAR_OPERATION_DATA_CHANGED;
  export type UNRECOGNIZED = typeof WearOperation.UNRECOGNIZED;
}

export const WearErrorCode = {
  WEAR_ERROR_CODE_UNSPECIFIED: "WEAR_ERROR_CODE_UNSPECIFIED",
  WEAR_ERROR_CODE_INVALID_VERSION: "WEAR_ERROR_CODE_INVALID_VERSION",
  WEAR_ERROR_CODE_UNKNOWN_OPERATION: "WEAR_ERROR_CODE_UNKNOWN_OPERATION",
  WEAR_ERROR_CODE_INVALID_PAYLOAD: "WEAR_ERROR_CODE_INVALID_PAYLOAD",
  WEAR_ERROR_CODE_UNAUTHENTICATED: "WEAR_ERROR_CODE_UNAUTHENTICATED",
  WEAR_ERROR_CODE_NOT_FOUND: "WEAR_ERROR_CODE_NOT_FOUND",
  WEAR_ERROR_CODE_REJECTED: "WEAR_ERROR_CODE_REJECTED",
  WEAR_ERROR_CODE_TIMEOUT: "WEAR_ERROR_CODE_TIMEOUT",
  WEAR_ERROR_CODE_DISCONNECTED: "WEAR_ERROR_CODE_DISCONNECTED",
  WEAR_ERROR_CODE_UNAVAILABLE: "WEAR_ERROR_CODE_UNAVAILABLE",
  WEAR_ERROR_CODE_NETWORK: "WEAR_ERROR_CODE_NETWORK",
  WEAR_ERROR_CODE_INTERNAL: "WEAR_ERROR_CODE_INTERNAL",
  WEAR_ERROR_CODE_MALFORMED_RESPONSE: "WEAR_ERROR_CODE_MALFORMED_RESPONSE",
  WEAR_ERROR_CODE_PLATFORM: "WEAR_ERROR_CODE_PLATFORM",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type WearErrorCode = typeof WearErrorCode[keyof typeof WearErrorCode];

export namespace WearErrorCode {
  export type WEAR_ERROR_CODE_UNSPECIFIED = typeof WearErrorCode.WEAR_ERROR_CODE_UNSPECIFIED;
  export type WEAR_ERROR_CODE_INVALID_VERSION = typeof WearErrorCode.WEAR_ERROR_CODE_INVALID_VERSION;
  export type WEAR_ERROR_CODE_UNKNOWN_OPERATION = typeof WearErrorCode.WEAR_ERROR_CODE_UNKNOWN_OPERATION;
  export type WEAR_ERROR_CODE_INVALID_PAYLOAD = typeof WearErrorCode.WEAR_ERROR_CODE_INVALID_PAYLOAD;
  export type WEAR_ERROR_CODE_UNAUTHENTICATED = typeof WearErrorCode.WEAR_ERROR_CODE_UNAUTHENTICATED;
  export type WEAR_ERROR_CODE_NOT_FOUND = typeof WearErrorCode.WEAR_ERROR_CODE_NOT_FOUND;
  export type WEAR_ERROR_CODE_REJECTED = typeof WearErrorCode.WEAR_ERROR_CODE_REJECTED;
  export type WEAR_ERROR_CODE_TIMEOUT = typeof WearErrorCode.WEAR_ERROR_CODE_TIMEOUT;
  export type WEAR_ERROR_CODE_DISCONNECTED = typeof WearErrorCode.WEAR_ERROR_CODE_DISCONNECTED;
  export type WEAR_ERROR_CODE_UNAVAILABLE = typeof WearErrorCode.WEAR_ERROR_CODE_UNAVAILABLE;
  export type WEAR_ERROR_CODE_NETWORK = typeof WearErrorCode.WEAR_ERROR_CODE_NETWORK;
  export type WEAR_ERROR_CODE_INTERNAL = typeof WearErrorCode.WEAR_ERROR_CODE_INTERNAL;
  export type WEAR_ERROR_CODE_MALFORMED_RESPONSE = typeof WearErrorCode.WEAR_ERROR_CODE_MALFORMED_RESPONSE;
  export type WEAR_ERROR_CODE_PLATFORM = typeof WearErrorCode.WEAR_ERROR_CODE_PLATFORM;
  export type UNRECOGNIZED = typeof WearErrorCode.UNRECOGNIZED;
}

export interface WearError {
  code: WearErrorCode;
  message: string;
  retryable: boolean;
}

export interface MealLogRequest {
  meal?: LoggedMeal | undefined;
  operationId: string;
  favoriteMealId?: number | undefined;
}

export interface MealDeleteRequest {
  mealId: number;
}

export interface TodayMealsRequest {
}

export interface CalorieGoalRequest {
}

export interface UserProfileRequest {
}

export interface FavoritesRequest {
}

export interface AuthSessionRequest {
}

export interface DetectTextRequest {
  textDescription: string;
}

export interface WearRequest {
  mealLog?: MealLogRequest | undefined;
  mealDelete?: MealDeleteRequest | undefined;
  todayMeals?: TodayMealsRequest | undefined;
  calorieGoal?: CalorieGoalRequest | undefined;
  userProfile?: UserProfileRequest | undefined;
  favorites?: FavoritesRequest | undefined;
  authSession?: AuthSessionRequest | undefined;
  detectText?: DetectTextRequest | undefined;
}

export interface MealLogResponse {
}

export interface MealDeleteResponse {
}

export interface TodayMealsResponse {
  meals: LoggedMeal[];
}

export interface CalorieGoalResponse {
  goal?: number | undefined;
}

export interface UserProfileResponse {
  profile?: UserProfile | undefined;
}

export interface FavoritesResponse {
  favorites: FavoriteMeal[];
}

export interface WearAuthSession {
  uid: string;
  authToken: string;
  isAnonymous: boolean;
  syncedAt: string;
}

export interface AuthSessionResponse {
  session?: WearAuthSession | undefined;
}

export interface DetectTextResponse {
  response?: MealDetectionResponse | undefined;
}

export interface WearResponse {
  error?: WearError | undefined;
  mealLog?: MealLogResponse | undefined;
  mealDelete?: MealDeleteResponse | undefined;
  todayMeals?: TodayMealsResponse | undefined;
  calorieGoal?: CalorieGoalResponse | undefined;
  userProfile?: UserProfileResponse | undefined;
  favorites?: FavoritesResponse | undefined;
  authSession?: AuthSessionResponse | undefined;
  detectText?: DetectTextResponse | undefined;
}

export interface DataChangedEvent {
  operations: WearOperation[];
}

export interface WearEvent {
  dataChanged?: DataChangedEvent | undefined;
}

export interface WearEnvelope {
  version: number;
  requestId: string;
  operation: WearOperation;
  request?: WearRequest | undefined;
  response?: WearResponse | undefined;
  event?: WearEvent | undefined;
}
