// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v7.34.1
// source: protos/meal/meal.proto

/* eslint-disable */

export const protobufPackage = "meal";

export const MealType = {
  UNKNOWN: "UNKNOWN",
  BREAKFAST: "BREAKFAST",
  LUNCH: "LUNCH",
  DINNER: "DINNER",
  SNACK: "SNACK",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type MealType = typeof MealType[keyof typeof MealType];

export namespace MealType {
  export type UNKNOWN = typeof MealType.UNKNOWN;
  export type BREAKFAST = typeof MealType.BREAKFAST;
  export type LUNCH = typeof MealType.LUNCH;
  export type DINNER = typeof MealType.DINNER;
  export type SNACK = typeof MealType.SNACK;
  export type UNRECOGNIZED = typeof MealType.UNRECOGNIZED;
}

export const HealthScore = {
  HEALTHY: "HEALTHY",
  NEUTRAL: "NEUTRAL",
  UNHEALTHY: "UNHEALTHY",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type HealthScore = typeof HealthScore[keyof typeof HealthScore];

export namespace HealthScore {
  export type HEALTHY = typeof HealthScore.HEALTHY;
  export type NEUTRAL = typeof HealthScore.NEUTRAL;
  export type UNHEALTHY = typeof HealthScore.UNHEALTHY;
  export type UNRECOGNIZED = typeof HealthScore.UNRECOGNIZED;
}

export const CalorieConfidence = {
  UNSPECIFIED: "UNSPECIFIED",
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CalorieConfidence = typeof CalorieConfidence[keyof typeof CalorieConfidence];

export namespace CalorieConfidence {
  export type UNSPECIFIED = typeof CalorieConfidence.UNSPECIFIED;
  export type LOW = typeof CalorieConfidence.LOW;
  export type MEDIUM = typeof CalorieConfidence.MEDIUM;
  export type HIGH = typeof CalorieConfidence.HIGH;
  export type UNRECOGNIZED = typeof CalorieConfidence.UNRECOGNIZED;
}

export interface MealMacro {
  calories: number;
  carbs: number;
  protein: number;
  fat: number;
  fiber: number;
}

export interface MealHealth {
  healthScore: HealthScore;
  healthScoreReason?: string | undefined;
}

export interface Meal {
  name: string;
  quantity: string;
  type: MealType;
  macros?: MealMacro | undefined;
  health?: MealHealth | undefined;
}
