# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calorify/sync.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'calorify/sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from calorify import models_pb2 as calorify_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x61lorify/sync.proto\x12\x0b\x63\x61lorify.v1\x1a\x15\x63\x61lorify/models.proto\"V\n\nDeleteMeal\x12\x16\n\tclient_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08local_id\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x0c\n\n_client_idB\x0b\n\t_local_id\"\x9a\x02\n\x06SyncOp\x12\x17\n\x0fidempotency_key\x18\x01 \x01(\t\x12(\n\x07op_type\x18\x02 \x01(\x0e\x32\x17.calorify.v1.SyncOpType\x12\x12\n\ncreated_at\x18\x03 \x01(\x03\x12%\n\x04meal\x18\x04 \x01(\x0b\x32\x15.calorify.v1.MealInfoH\x00\x12.\n\x0b\x64\x65lete_meal\x18\x05 \x01(\x0b\x32\x17.calorify.v1.DeleteMealH\x00\x12+\n\x07profile\x18\x06 \x01(\x0b\x32\x18.calorify.v1.UserProfileH\x00\x12*\n\tfcm_token\x18\x07 \x01(\x0b\x32\x15.calorify.v1.FcmTokenH\x00\x42\t\n\x07payload\"-\n\tSyncBatch\x12 \n\x03ops\x18\x01 \x03(\x0b\x32\x13.calorify.v1.SyncOp\"X\n\nSyncResult\x12\x17\n\x0fidempotency_key\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x11\n\tremote_id\x18\x04 \x01(\t\"3\n\x07SyncAck\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.calorify.v1.SyncResult*\xa3\x01\n\nSyncOpType\x12\x1c\n\x18SYNC_OP_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18SYNC_OP_TYPE_UPSERT_MEAL\x10\x01\x12\x1c\n\x18SYNC_OP_TYPE_DELETE_MEAL\x10\x02\x12\x1f\n\x1bSYNC_OP_TYPE_UPSERT_PROFILE\x10\x03\x12\x1a\n\x16SYNC_OP_TYPE_FCM_TOKEN\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calorify.sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCOPTYPE']._serialized_start=623
  _globals['_SYNCOPTYPE']._serialized_end=786
  _globals['_DELETEMEAL']._serialized_start=59
  _globals['_DELETEMEAL']._serialized_end=145
  _globals['_SYNCOP']._serialized_start=148
  _globals['_SYNCOP']._serialized_end=430
  _globals['_SYNCBATCH']._serialized_start=432
  _globals['_SYNCBATCH']._serialized_end=477
  _globals['_SYNCRESULT']._serialized_start=479
  _globals['_SYNCRESULT']._serialized_end=567
  _globals['_SYNCACK']._serialized_start=569
  _globals['_SYNCACK']._serialized_end=620
# @@protoc_insertion_point(module_scope)
