syntax = "proto3";

package calorify;

import "protos/meal/meal.proto";

import "protos/calorify/ai_meal_summary_trend.proto";




message ApiResult {
  bool ok = 1;
  string message = 2;
}


message AiMealSummaryResponse {
  optional string summary = 1;
  optional string generated_at = 2; 
  int32 meal_count = 3;
  repeated string top_foods = 4;
  int32 macro_balance_score = 5;
  calorify.ai_meal_summary.AiMealSummaryTrend trend = 6;
}


message MealAnalysisTipsResponse {
  int32 version = 1;
  repeated string tips = 2;
}


enum MealAnalysisFeedbackSignal {
  SIGNAL_UNSPECIFIED = 0;
  UP = 1;
  DOWN = 2;
}


message MealAnalysisFeedbackRequest {
  string analysis_id = 1;
  MealAnalysisFeedbackSignal signal = 2;
}


message MealAnalysisConfirmLogRequest {
  string analysis_id = 1;
  string logged_at = 2;
  meal.Meal meal = 3;
}


message MealClarificationAnswer {
  string clarification_id = 1;
  string selected_option_id = 2;
}

message MealAnalysisClarifyRequest {
  string analysis_id = 1;
  repeated MealClarificationAnswer answers = 2;
}


message MealAnalysisMealTypeRequest {
  string analysis_id = 1;
  meal.MealType meal_type = 2;
}


enum MealReanalyzeFeedbackIssue {
  ISSUE_UNSPECIFIED = 0;
  FOOD_IDENTIFICATION = 1;
  PORTION_SIZE = 2;
  CALORIE_DISTRIBUTION = 3;
  MACROS_WRONG = 4;
  MISSING_ITEMS = 5;
  EXTRA_ITEMS = 6;
  OTHER = 7;
}

message MealAnalysisReanalyzeRequest {
  string analysis_id = 1;
  repeated MealReanalyzeFeedbackIssue issues = 2;
  optional string other_text = 3;
}