syntax = "proto3";

package calorify;

import "protos/meal/meal.proto";

import "protos/calorify/ai_meal_summary_trend.proto";
import "protos/calorify/meal_analysis_pipeline.proto";




message ApiResult {
  bool ok = 1;
  string message = 2;
}


message AiMealSummaryResponse {
  optional string summary = 1;
  optional string generated_at = 2; 
  int32 meal_count = 3;
  repeated string top_foods = 4;
  int32 macro_balance_score = 5;
  calorify.ai_meal_summary.AiMealSummaryTrend trend = 6;
}


message MealAnalysisTipsResponse {
  int32 version = 1;
  repeated string tips = 2;
}


message MealAnalysisTextRequest {
  optional string analysis_id = 1;
  string text_description = 2;
  bool local_attempted = 3;
  MealAnalysisFallbackReason fallback_reason = 4;
  optional string local_attempt_id = 5;
  optional int64 local_attempt_started_at_epoch_ms = 6;
  optional int64 local_attempt_completed_at_epoch_ms = 7;
}


message MealAnalysisImageRequest {
  optional string analysis_id = 1;
  string image_url = 2;
}

message MealAnalysisProposalRequest {
  string analysis_id = 1;
  IngredientProposalV1 proposal = 2;
  string local_attempt_id = 3;
  int64 local_attempt_started_at_epoch_ms = 4;
  int64 local_attempt_completed_at_epoch_ms = 5;
  MealAnalysisFallbackReason fallback_reason = 6;
}

message LocalInferenceCapabilityPolicy {
  reserved 1, 3, 4, 5, 6;
  reserved "policy_version", "image_enabled", "local_nutrition_enabled", "private_modes_enabled", "max_age_seconds";
  bool text_enabled = 2;
  optional string local_nutrition_manifest_url = 7;
}


message LocalNutritionPackManifest {
  uint32 schema_version = 1;
  string pack_version = 2;
  string dataset_version = 3;
  string object_name = 4;
  int64 size_bytes = 5;
  reserved 6, 7, 8, 9;
  reserved "signature", "signing_key_id", "created_at_epoch_ms";
  uint32 record_count = 10;
  string calculation_version = 11;
}


message LocalNutritionLookup {
  string row_id = 1;
  string canonical_hint = 2;
  string preparation = 3;
}


message CacheableNutritionRecord {
  string row_id = 1;
  string fdc_id = 2;
  string description = 3;
  string normalized_name = 4;
  string data_type = 5;
  PipelineMacros nutrients_per_100g = 6;
  string dataset_version = 7;
  int64 retrieved_at_epoch_ms = 8;
  reserved 9;
  repeated string lookup_keys = 10;
  string match_type = 11;
  double match_confidence = 12;
}


message LocalNutritionResolveRequest {
  string analysis_id = 1;
  repeated LocalNutritionLookup lookups = 2;
}


message LocalNutritionResolveResponse {
  string analysis_id = 1;
  repeated CacheableNutritionRecord records = 2;
  repeated string unresolved_row_ids = 3;
}


enum MealAnalysisFeedbackSignal {
  SIGNAL_UNSPECIFIED = 0;
  UP = 1;
  DOWN = 2;
}


message MealAnalysisFeedbackRequest {
  string analysis_id = 1;
  MealAnalysisFeedbackSignal signal = 2;
}


message MealAnalysisConfirmLogRequest {
  string analysis_id = 1;
  string logged_at = 2;
  meal.Meal meal = 3;
  // Reuses the confirmation endpoint for the inverse local mutation. When
  // true, logged_at and meal are intentionally omitted.
  bool deleted = 4;
}


message MealClarificationAnswer {
  string clarification_id = 1;
  string selected_option_id = 2;
}

message MealAnalysisClarifyRequest {
  string analysis_id = 1;
  repeated MealClarificationAnswer answers = 2;
}


message MealAnalysisResumeRequest {
  string analysis_id = 1;
}


message MealAnalysisMealTypeRequest {
  string analysis_id = 1;
  meal.MealType meal_type = 2;
}


enum MealReanalyzeFeedbackIssue {
  ISSUE_UNSPECIFIED = 0;
  FOOD_IDENTIFICATION = 1;
  PORTION_SIZE = 2;
  CALORIE_DISTRIBUTION = 3;
  MACROS_WRONG = 4;
  MISSING_ITEMS = 5;
  EXTRA_ITEMS = 6;
  OTHER = 7;
}

message MealAnalysisReanalyzeRequest {
  string analysis_id = 1;
  repeated MealReanalyzeFeedbackIssue issues = 2;
  optional string other_text = 3;
  optional string new_analysis_id = 4;
}
