// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.27.3
// source: protos/calorify/ai_meal_summary_trend.proto

/* eslint-disable */

export const protobufPackage = "calorify.ai_meal_summary";

export const AiMealSummaryTrend = {
  UNSPECIFIED: "UNSPECIFIED",
  UP: "UP",
  DOWN: "DOWN",
  STEADY: "STEADY",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type AiMealSummaryTrend = typeof AiMealSummaryTrend[keyof typeof AiMealSummaryTrend];

export namespace AiMealSummaryTrend {
  export type UNSPECIFIED = typeof AiMealSummaryTrend.UNSPECIFIED;
  export type UP = typeof AiMealSummaryTrend.UP;
  export type DOWN = typeof AiMealSummaryTrend.DOWN;
  export type STEADY = typeof AiMealSummaryTrend.STEADY;
  export type UNRECOGNIZED = typeof AiMealSummaryTrend.UNRECOGNIZED;
}
