// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v7.34.1
// source: protos/calorify/app_banner.proto

/* eslint-disable */

export const protobufPackage = "calorify";

export const BannerPriority = { LOW: "LOW", MEDIUM: "MEDIUM", HIGH: "HIGH", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type BannerPriority = typeof BannerPriority[keyof typeof BannerPriority];

export namespace BannerPriority {
  export type LOW = typeof BannerPriority.LOW;
  export type MEDIUM = typeof BannerPriority.MEDIUM;
  export type HIGH = typeof BannerPriority.HIGH;
  export type UNRECOGNIZED = typeof BannerPriority.UNRECOGNIZED;
}

export interface Banner {
  enabled: boolean;
  messagesByLocale: { [key: string]: string };
  priority?: BannerPriority | undefined;
  dismissible: boolean;
  linkUrl?: string | undefined;
  minimumBuildInclusive?: number | undefined;
  maximumBuildExclusive?: number | undefined;
  createdAt?: number | undefined;
}

export interface Banner_MessagesByLocaleEntry {
  key: string;
  value: string;
}
