// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.27.3
// source: protos/calorify/common.proto

/* eslint-disable */

export const protobufPackage = "calorify";

export interface FcmToken {
  token: string;
  deviceType?: string | undefined;
}
