// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v7.34.1
// source: protos/calorify/http_api.proto

/* eslint-disable */
import type { Meal, MealType } from "../meal/meal";
import type { AiMealSummaryTrend } from "./ai_meal_summary_trend";

export const protobufPackage = "calorify";

/** POST /api/v2/food/feedback — proto3 JSON uses enumerator names ("SIGNAL_UNSPECIFIED", "UP", "DOWN", …). */
export const MealAnalysisFeedbackSignal = {
  SIGNAL_UNSPECIFIED: "SIGNAL_UNSPECIFIED",
  UP: "UP",
  DOWN: "DOWN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type MealAnalysisFeedbackSignal = typeof MealAnalysisFeedbackSignal[keyof typeof MealAnalysisFeedbackSignal];

export namespace MealAnalysisFeedbackSignal {
  export type SIGNAL_UNSPECIFIED = typeof MealAnalysisFeedbackSignal.SIGNAL_UNSPECIFIED;
  export type UP = typeof MealAnalysisFeedbackSignal.UP;
  export type DOWN = typeof MealAnalysisFeedbackSignal.DOWN;
  export type UNRECOGNIZED = typeof MealAnalysisFeedbackSignal.UNRECOGNIZED;
}

/** POST /api/v2/food/reanalyze — JSON array uses enumerator names (e.g. "PORTION_SIZE"). */
export const MealReanalyzeFeedbackIssue = {
  ISSUE_UNSPECIFIED: "ISSUE_UNSPECIFIED",
  FOOD_IDENTIFICATION: "FOOD_IDENTIFICATION",
  PORTION_SIZE: "PORTION_SIZE",
  CALORIE_DISTRIBUTION: "CALORIE_DISTRIBUTION",
  MACROS_WRONG: "MACROS_WRONG",
  MISSING_ITEMS: "MISSING_ITEMS",
  EXTRA_ITEMS: "EXTRA_ITEMS",
  OTHER: "OTHER",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type MealReanalyzeFeedbackIssue = typeof MealReanalyzeFeedbackIssue[keyof typeof MealReanalyzeFeedbackIssue];

export namespace MealReanalyzeFeedbackIssue {
  export type ISSUE_UNSPECIFIED = typeof MealReanalyzeFeedbackIssue.ISSUE_UNSPECIFIED;
  export type FOOD_IDENTIFICATION = typeof MealReanalyzeFeedbackIssue.FOOD_IDENTIFICATION;
  export type PORTION_SIZE = typeof MealReanalyzeFeedbackIssue.PORTION_SIZE;
  export type CALORIE_DISTRIBUTION = typeof MealReanalyzeFeedbackIssue.CALORIE_DISTRIBUTION;
  export type MACROS_WRONG = typeof MealReanalyzeFeedbackIssue.MACROS_WRONG;
  export type MISSING_ITEMS = typeof MealReanalyzeFeedbackIssue.MISSING_ITEMS;
  export type EXTRA_ITEMS = typeof MealReanalyzeFeedbackIssue.EXTRA_ITEMS;
  export type OTHER = typeof MealReanalyzeFeedbackIssue.OTHER;
  export type UNRECOGNIZED = typeof MealReanalyzeFeedbackIssue.UNRECOGNIZED;
}

/**
 * Standard JSON body for simple API acks (2xx) and application/json errors (4xx/5xx)
 * when no other payload is returned: `ok` plus a human-readable `message`.
 * Used for e.g. POST /api/v1/user/profile, POST /api/v2/food/feedback, /confirm-log.
 */
export interface ApiResult {
  ok: boolean;
  message: string;
}

/** GET /api/v1/food/ai-summary */
export interface AiMealSummaryResponse {
  summary?:
    | string
    | undefined;
  /** JSON key: generatedAt */
  generatedAt?: string | undefined;
  mealCount: number;
  topFoods: string[];
  macroBalanceScore: number;
  trend: AiMealSummaryTrend;
}

/** GET /api/v1/food/meal-analysis-tips */
export interface MealAnalysisTipsResponse {
  version: number;
  tips: string[];
}

/** POST /api/v2/food/feedback */
export interface MealAnalysisFeedbackRequest {
  analysisId: string;
  signal: MealAnalysisFeedbackSignal;
}

/** POST /api/v2/food/confirm-log */
export interface MealAnalysisConfirmLogRequest {
  analysisId: string;
  loggedAt: string;
  meal?: Meal | undefined;
}

/** POST /api/v2/food/clarify (proto3 JSON uses camelCase for nested keys). */
export interface MealClarificationAnswer {
  ingredientName: string;
  selectedOptionIndex: number;
}

export interface MealAnalysisClarifyRequest {
  analysisId: string;
  answers: MealClarificationAnswer[];
}

/** POST /api/v2/food/meal-type */
export interface MealAnalysisMealTypeRequest {
  analysisId: string;
  mealType: MealType;
}

export interface MealAnalysisReanalyzeRequest {
  analysisId: string;
  issues: MealReanalyzeFeedbackIssue[];
  otherText?: string | undefined;
}
