// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v7.34.1
// source: protos/calorify/meal_detection.proto

/* eslint-disable */
import type { CalorieConfidence, Meal } from "../meal/meal";

export const protobufPackage = "calorify";

export interface MealMetadata {
  imageUrl?: string | undefined;
  mealDescription?: string | undefined;
}

export interface MealDetectionResult {
  mealIdentified: boolean;
  calorieConfidence: CalorieConfidence;
  tip: string;
  meal?: Meal | undefined;
  metadata?: MealMetadata | undefined;
}

export interface MealDetectionResponse {
  result?: MealDetectionResult | undefined;
}
