// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v7.34.1
// source: protos/calorify/meal_analysis_pipeline.proto

/* eslint-disable */
import type { CalorieConfidence, HealthScore, MealType } from "../meal/meal";

export const protobufPackage = "calorify";

export const PipelineStep = {
  PIPELINE_STEP_UNSPECIFIED: "PIPELINE_STEP_UNSPECIFIED",
  STARTED: "STARTED",
  DECOMPOSITION: "DECOMPOSITION",
  INGREDIENTS: "INGREDIENTS",
  UNCERTAINTY: "UNCERTAINTY",
  MEAL_TYPE_QUESTION: "MEAL_TYPE_QUESTION",
  RESULT: "RESULT",
  ERROR: "ERROR",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type PipelineStep = typeof PipelineStep[keyof typeof PipelineStep];

export namespace PipelineStep {
  export type PIPELINE_STEP_UNSPECIFIED = typeof PipelineStep.PIPELINE_STEP_UNSPECIFIED;
  export type STARTED = typeof PipelineStep.STARTED;
  export type DECOMPOSITION = typeof PipelineStep.DECOMPOSITION;
  export type INGREDIENTS = typeof PipelineStep.INGREDIENTS;
  export type UNCERTAINTY = typeof PipelineStep.UNCERTAINTY;
  export type MEAL_TYPE_QUESTION = typeof PipelineStep.MEAL_TYPE_QUESTION;
  export type RESULT = typeof PipelineStep.RESULT;
  export type ERROR = typeof PipelineStep.ERROR;
  export type UNRECOGNIZED = typeof PipelineStep.UNRECOGNIZED;
}

export const PortionKind = {
  PORTION_KIND_UNSPECIFIED: "PORTION_KIND_UNSPECIFIED",
  /** COUNT - discrete units: roti, slice, egg, piece */
  COUNT: "COUNT",
  /** BULK - spoon/cup/bowl foods: rice, dal, sabzi, sauces */
  BULK: "BULK",
  /** PINCH - trace amounts: salt, spices, garnishes */
  PINCH: "PINCH",
  /** COUNT_QUESTION - synthetic; clarification asks "how many?" */
  COUNT_QUESTION: "COUNT_QUESTION",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type PortionKind = typeof PortionKind[keyof typeof PortionKind];

export namespace PortionKind {
  export type PORTION_KIND_UNSPECIFIED = typeof PortionKind.PORTION_KIND_UNSPECIFIED;
  export type COUNT = typeof PortionKind.COUNT;
  export type BULK = typeof PortionKind.BULK;
  export type PINCH = typeof PortionKind.PINCH;
  export type COUNT_QUESTION = typeof PortionKind.COUNT_QUESTION;
  export type UNRECOGNIZED = typeof PortionKind.UNRECOGNIZED;
}

export const AnalysisModality = {
  ANALYSIS_MODALITY_UNSPECIFIED: "ANALYSIS_MODALITY_UNSPECIFIED",
  ANALYSIS_MODALITY_TEXT: "ANALYSIS_MODALITY_TEXT",
  ANALYSIS_MODALITY_IMAGE: "ANALYSIS_MODALITY_IMAGE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type AnalysisModality = typeof AnalysisModality[keyof typeof AnalysisModality];

export namespace AnalysisModality {
  export type ANALYSIS_MODALITY_UNSPECIFIED = typeof AnalysisModality.ANALYSIS_MODALITY_UNSPECIFIED;
  export type ANALYSIS_MODALITY_TEXT = typeof AnalysisModality.ANALYSIS_MODALITY_TEXT;
  export type ANALYSIS_MODALITY_IMAGE = typeof AnalysisModality.ANALYSIS_MODALITY_IMAGE;
  export type UNRECOGNIZED = typeof AnalysisModality.UNRECOGNIZED;
}

export const InterpretationOrigin = {
  INTERPRETATION_ORIGIN_UNSPECIFIED: "INTERPRETATION_ORIGIN_UNSPECIFIED",
  INTERPRETATION_ORIGIN_CLOUD_MODEL: "INTERPRETATION_ORIGIN_CLOUD_MODEL",
  INTERPRETATION_ORIGIN_LOCAL_NANO: "INTERPRETATION_ORIGIN_LOCAL_NANO",
  INTERPRETATION_ORIGIN_MANUAL: "INTERPRETATION_ORIGIN_MANUAL",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type InterpretationOrigin = typeof InterpretationOrigin[keyof typeof InterpretationOrigin];

export namespace InterpretationOrigin {
  export type INTERPRETATION_ORIGIN_UNSPECIFIED = typeof InterpretationOrigin.INTERPRETATION_ORIGIN_UNSPECIFIED;
  export type INTERPRETATION_ORIGIN_CLOUD_MODEL = typeof InterpretationOrigin.INTERPRETATION_ORIGIN_CLOUD_MODEL;
  export type INTERPRETATION_ORIGIN_LOCAL_NANO = typeof InterpretationOrigin.INTERPRETATION_ORIGIN_LOCAL_NANO;
  export type INTERPRETATION_ORIGIN_MANUAL = typeof InterpretationOrigin.INTERPRETATION_ORIGIN_MANUAL;
  export type UNRECOGNIZED = typeof InterpretationOrigin.UNRECOGNIZED;
}

export const NutritionOrigin = {
  NUTRITION_ORIGIN_UNSPECIFIED: "NUTRITION_ORIGIN_UNSPECIFIED",
  NUTRITION_ORIGIN_BUNDLED_USDA: "NUTRITION_ORIGIN_BUNDLED_USDA",
  NUTRITION_ORIGIN_CACHED_USDA: "NUTRITION_ORIGIN_CACHED_USDA",
  NUTRITION_ORIGIN_REMOTE_USDA: "NUTRITION_ORIGIN_REMOTE_USDA",
  NUTRITION_ORIGIN_DETERMINISTIC_CONSTANT: "NUTRITION_ORIGIN_DETERMINISTIC_CONSTANT",
  NUTRITION_ORIGIN_LLM_FALLBACK: "NUTRITION_ORIGIN_LLM_FALLBACK",
  NUTRITION_ORIGIN_UNRESOLVED: "NUTRITION_ORIGIN_UNRESOLVED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type NutritionOrigin = typeof NutritionOrigin[keyof typeof NutritionOrigin];

export namespace NutritionOrigin {
  export type NUTRITION_ORIGIN_UNSPECIFIED = typeof NutritionOrigin.NUTRITION_ORIGIN_UNSPECIFIED;
  export type NUTRITION_ORIGIN_BUNDLED_USDA = typeof NutritionOrigin.NUTRITION_ORIGIN_BUNDLED_USDA;
  export type NUTRITION_ORIGIN_CACHED_USDA = typeof NutritionOrigin.NUTRITION_ORIGIN_CACHED_USDA;
  export type NUTRITION_ORIGIN_REMOTE_USDA = typeof NutritionOrigin.NUTRITION_ORIGIN_REMOTE_USDA;
  export type NUTRITION_ORIGIN_DETERMINISTIC_CONSTANT = typeof NutritionOrigin.NUTRITION_ORIGIN_DETERMINISTIC_CONSTANT;
  export type NUTRITION_ORIGIN_LLM_FALLBACK = typeof NutritionOrigin.NUTRITION_ORIGIN_LLM_FALLBACK;
  export type NUTRITION_ORIGIN_UNRESOLVED = typeof NutritionOrigin.NUTRITION_ORIGIN_UNRESOLVED;
  export type UNRECOGNIZED = typeof NutritionOrigin.UNRECOGNIZED;
}

export const CalculationOrigin = {
  CALCULATION_ORIGIN_UNSPECIFIED: "CALCULATION_ORIGIN_UNSPECIFIED",
  CALCULATION_ORIGIN_LOCAL_DETERMINISTIC: "CALCULATION_ORIGIN_LOCAL_DETERMINISTIC",
  CALCULATION_ORIGIN_SERVER_DETERMINISTIC: "CALCULATION_ORIGIN_SERVER_DETERMINISTIC",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CalculationOrigin = typeof CalculationOrigin[keyof typeof CalculationOrigin];

export namespace CalculationOrigin {
  export type CALCULATION_ORIGIN_UNSPECIFIED = typeof CalculationOrigin.CALCULATION_ORIGIN_UNSPECIFIED;
  export type CALCULATION_ORIGIN_LOCAL_DETERMINISTIC = typeof CalculationOrigin.CALCULATION_ORIGIN_LOCAL_DETERMINISTIC;
  export type CALCULATION_ORIGIN_SERVER_DETERMINISTIC =
    typeof CalculationOrigin.CALCULATION_ORIGIN_SERVER_DETERMINISTIC;
  export type UNRECOGNIZED = typeof CalculationOrigin.UNRECOGNIZED;
}

export const IngredientFieldOrigin = {
  INGREDIENT_FIELD_ORIGIN_UNSPECIFIED: "INGREDIENT_FIELD_ORIGIN_UNSPECIFIED",
  INGREDIENT_FIELD_ORIGIN_USER_INPUT: "INGREDIENT_FIELD_ORIGIN_USER_INPUT",
  INGREDIENT_FIELD_ORIGIN_LOCAL_MODEL: "INGREDIENT_FIELD_ORIGIN_LOCAL_MODEL",
  INGREDIENT_FIELD_ORIGIN_CLOUD_MODEL: "INGREDIENT_FIELD_ORIGIN_CLOUD_MODEL",
  INGREDIENT_FIELD_ORIGIN_USER_EDIT: "INGREDIENT_FIELD_ORIGIN_USER_EDIT",
  INGREDIENT_FIELD_ORIGIN_DETERMINISTIC: "INGREDIENT_FIELD_ORIGIN_DETERMINISTIC",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type IngredientFieldOrigin = typeof IngredientFieldOrigin[keyof typeof IngredientFieldOrigin];

export namespace IngredientFieldOrigin {
  export type INGREDIENT_FIELD_ORIGIN_UNSPECIFIED = typeof IngredientFieldOrigin.INGREDIENT_FIELD_ORIGIN_UNSPECIFIED;
  export type INGREDIENT_FIELD_ORIGIN_USER_INPUT = typeof IngredientFieldOrigin.INGREDIENT_FIELD_ORIGIN_USER_INPUT;
  export type INGREDIENT_FIELD_ORIGIN_LOCAL_MODEL = typeof IngredientFieldOrigin.INGREDIENT_FIELD_ORIGIN_LOCAL_MODEL;
  export type INGREDIENT_FIELD_ORIGIN_CLOUD_MODEL = typeof IngredientFieldOrigin.INGREDIENT_FIELD_ORIGIN_CLOUD_MODEL;
  export type INGREDIENT_FIELD_ORIGIN_USER_EDIT = typeof IngredientFieldOrigin.INGREDIENT_FIELD_ORIGIN_USER_EDIT;
  export type INGREDIENT_FIELD_ORIGIN_DETERMINISTIC =
    typeof IngredientFieldOrigin.INGREDIENT_FIELD_ORIGIN_DETERMINISTIC;
  export type UNRECOGNIZED = typeof IngredientFieldOrigin.UNRECOGNIZED;
}

export const AnalysisAttemptStatus = {
  ANALYSIS_ATTEMPT_STATUS_UNSPECIFIED: "ANALYSIS_ATTEMPT_STATUS_UNSPECIFIED",
  ANALYSIS_ATTEMPT_STATUS_STARTED: "ANALYSIS_ATTEMPT_STATUS_STARTED",
  ANALYSIS_ATTEMPT_STATUS_ACCEPTED: "ANALYSIS_ATTEMPT_STATUS_ACCEPTED",
  ANALYSIS_ATTEMPT_STATUS_FAILED: "ANALYSIS_ATTEMPT_STATUS_FAILED",
  ANALYSIS_ATTEMPT_STATUS_CANCELLED: "ANALYSIS_ATTEMPT_STATUS_CANCELLED",
  ANALYSIS_ATTEMPT_STATUS_SUPERSEDED: "ANALYSIS_ATTEMPT_STATUS_SUPERSEDED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type AnalysisAttemptStatus = typeof AnalysisAttemptStatus[keyof typeof AnalysisAttemptStatus];

export namespace AnalysisAttemptStatus {
  export type ANALYSIS_ATTEMPT_STATUS_UNSPECIFIED = typeof AnalysisAttemptStatus.ANALYSIS_ATTEMPT_STATUS_UNSPECIFIED;
  export type ANALYSIS_ATTEMPT_STATUS_STARTED = typeof AnalysisAttemptStatus.ANALYSIS_ATTEMPT_STATUS_STARTED;
  export type ANALYSIS_ATTEMPT_STATUS_ACCEPTED = typeof AnalysisAttemptStatus.ANALYSIS_ATTEMPT_STATUS_ACCEPTED;
  export type ANALYSIS_ATTEMPT_STATUS_FAILED = typeof AnalysisAttemptStatus.ANALYSIS_ATTEMPT_STATUS_FAILED;
  export type ANALYSIS_ATTEMPT_STATUS_CANCELLED = typeof AnalysisAttemptStatus.ANALYSIS_ATTEMPT_STATUS_CANCELLED;
  export type ANALYSIS_ATTEMPT_STATUS_SUPERSEDED = typeof AnalysisAttemptStatus.ANALYSIS_ATTEMPT_STATUS_SUPERSEDED;
  export type UNRECOGNIZED = typeof AnalysisAttemptStatus.UNRECOGNIZED;
}

export const MealAnalysisFallbackReason = {
  MEAL_ANALYSIS_FALLBACK_REASON_UNSPECIFIED: "MEAL_ANALYSIS_FALLBACK_REASON_UNSPECIFIED",
  MEAL_ANALYSIS_FALLBACK_REASON_NONE: "MEAL_ANALYSIS_FALLBACK_REASON_NONE",
  MEAL_ANALYSIS_FALLBACK_REASON_UNSUPPORTED_DEVICE: "MEAL_ANALYSIS_FALLBACK_REASON_UNSUPPORTED_DEVICE",
  MEAL_ANALYSIS_FALLBACK_REASON_MODEL_NOT_READY: "MEAL_ANALYSIS_FALLBACK_REASON_MODEL_NOT_READY",
  MEAL_ANALYSIS_FALLBACK_REASON_BUSY: "MEAL_ANALYSIS_FALLBACK_REASON_BUSY",
  MEAL_ANALYSIS_FALLBACK_REASON_QUOTA_LIMITED: "MEAL_ANALYSIS_FALLBACK_REASON_QUOTA_LIMITED",
  MEAL_ANALYSIS_FALLBACK_REASON_BACKGROUND_BLOCKED: "MEAL_ANALYSIS_FALLBACK_REASON_BACKGROUND_BLOCKED",
  MEAL_ANALYSIS_FALLBACK_REASON_THERMALLY_LIMITED: "MEAL_ANALYSIS_FALLBACK_REASON_THERMALLY_LIMITED",
  MEAL_ANALYSIS_FALLBACK_REASON_MODEL_UPDATING: "MEAL_ANALYSIS_FALLBACK_REASON_MODEL_UPDATING",
  MEAL_ANALYSIS_FALLBACK_REASON_ROLLOUT_DISABLED: "MEAL_ANALYSIS_FALLBACK_REASON_ROLLOUT_DISABLED",
  MEAL_ANALYSIS_FALLBACK_REASON_TIMED_OUT: "MEAL_ANALYSIS_FALLBACK_REASON_TIMED_OUT",
  MEAL_ANALYSIS_FALLBACK_REASON_INVALID_OUTPUT: "MEAL_ANALYSIS_FALLBACK_REASON_INVALID_OUTPUT",
  MEAL_ANALYSIS_FALLBACK_REASON_CANCELLED: "MEAL_ANALYSIS_FALLBACK_REASON_CANCELLED",
  MEAL_ANALYSIS_FALLBACK_REASON_LOCAL_NUTRITION_MISS: "MEAL_ANALYSIS_FALLBACK_REASON_LOCAL_NUTRITION_MISS",
  MEAL_ANALYSIS_FALLBACK_REASON_DATASET_INCOMPATIBLE: "MEAL_ANALYSIS_FALLBACK_REASON_DATASET_INCOMPATIBLE",
  MEAL_ANALYSIS_FALLBACK_REASON_USER_APPROVED: "MEAL_ANALYSIS_FALLBACK_REASON_USER_APPROVED",
  MEAL_ANALYSIS_FALLBACK_REASON_USER_DENIED: "MEAL_ANALYSIS_FALLBACK_REASON_USER_DENIED",
  MEAL_ANALYSIS_FALLBACK_REASON_UNKNOWN: "MEAL_ANALYSIS_FALLBACK_REASON_UNKNOWN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type MealAnalysisFallbackReason = typeof MealAnalysisFallbackReason[keyof typeof MealAnalysisFallbackReason];

export namespace MealAnalysisFallbackReason {
  export type MEAL_ANALYSIS_FALLBACK_REASON_UNSPECIFIED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_UNSPECIFIED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_NONE = typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_NONE;
  export type MEAL_ANALYSIS_FALLBACK_REASON_UNSUPPORTED_DEVICE =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_UNSUPPORTED_DEVICE;
  export type MEAL_ANALYSIS_FALLBACK_REASON_MODEL_NOT_READY =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_MODEL_NOT_READY;
  export type MEAL_ANALYSIS_FALLBACK_REASON_BUSY = typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_BUSY;
  export type MEAL_ANALYSIS_FALLBACK_REASON_QUOTA_LIMITED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_QUOTA_LIMITED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_BACKGROUND_BLOCKED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_BACKGROUND_BLOCKED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_THERMALLY_LIMITED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_THERMALLY_LIMITED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_MODEL_UPDATING =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_MODEL_UPDATING;
  export type MEAL_ANALYSIS_FALLBACK_REASON_ROLLOUT_DISABLED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_ROLLOUT_DISABLED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_TIMED_OUT =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_TIMED_OUT;
  export type MEAL_ANALYSIS_FALLBACK_REASON_INVALID_OUTPUT =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_INVALID_OUTPUT;
  export type MEAL_ANALYSIS_FALLBACK_REASON_CANCELLED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_CANCELLED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_LOCAL_NUTRITION_MISS =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_LOCAL_NUTRITION_MISS;
  export type MEAL_ANALYSIS_FALLBACK_REASON_DATASET_INCOMPATIBLE =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_DATASET_INCOMPATIBLE;
  export type MEAL_ANALYSIS_FALLBACK_REASON_USER_APPROVED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_USER_APPROVED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_USER_DENIED =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_USER_DENIED;
  export type MEAL_ANALYSIS_FALLBACK_REASON_UNKNOWN =
    typeof MealAnalysisFallbackReason.MEAL_ANALYSIS_FALLBACK_REASON_UNKNOWN;
  export type UNRECOGNIZED = typeof MealAnalysisFallbackReason.UNRECOGNIZED;
}

export interface PipelineCalorieBand {
  min: number;
  max: number;
}

export interface PipelineMacros {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface IngredientFieldProvenance {
  fieldName: string;
  origin: IngredientFieldOrigin;
}

/**
 * Models may propose identity and portion information only. Nutrient values
 * intentionally do not exist in this contract.
 */
export interface IngredientProposalItemV1 {
  rowId: string;
  rawName: string;
  canonicalHint: string;
  preparation: string;
  gramsEstimated: number;
  minGrams: number;
  maxGrams: number;
  notes: string;
  portionKind: PortionKind;
  count?: number | undefined;
  perUnitGrams?: number | undefined;
  perUnitMinGrams?: number | undefined;
  perUnitMaxGrams?: number | undefined;
  sizeSpecifiedByUser: boolean;
  confidence: number;
  fieldProvenance: IngredientFieldProvenance[];
}

export interface IngredientProposalV1 {
  schemaVersion: number;
  proposalId: string;
  modality: AnalysisModality;
  mealName: string;
  inferredMealType: MealType;
  mealTypeConfident: boolean;
  confidence: number;
  ingredients: IngredientProposalItemV1[];
  interpretationOrigin: InterpretationOrigin;
  modelName?: string | undefined;
  modelVersion?: string | undefined;
}

export interface AnalysisAttemptReceipt {
  attemptId: string;
  executorOrigin: InterpretationOrigin;
  startedAtEpochMs: number;
  completedAtEpochMs?: number | undefined;
  status: AnalysisAttemptStatus;
  fallbackReason: MealAnalysisFallbackReason;
}

export interface MealAnalysisReceipt {
  schemaVersion: number;
  proposalSchemaVersion: number;
  localAttempted: boolean;
  interpretationOrigin: InterpretationOrigin;
  nutritionOrigin: NutritionOrigin;
  calculationOrigin: CalculationOrigin;
  usdaDatasetVersion?: string | undefined;
  calculationVersion: string;
  attempts: AnalysisAttemptReceipt[];
  fallbackReason: MealAnalysisFallbackReason;
}

export interface PipelineMealHealth {
  healthScore: HealthScore;
  healthScoreReason: string;
}

export interface PipelineDecomposedIngredient {
  /** stable id per row; survives clarify replays */
  rowId: string;
  rawName: string;
  canonicalHint: string;
  /**
   * Total grams used downstream for macro math. Server enforces:
   *   if portion_kind == COUNT: grams_estimated = count * per_unit_grams
   */
  gramsEstimated: number;
  minGrams: number;
  maxGrams: number;
  notes: string;
  portionKind: PortionKind;
  /** fractional ok; null if not extracted */
  count?: number | undefined;
  perUnitGrams?: number | undefined;
  perUnitMinGrams?: number | undefined;
  perUnitMaxGrams?: number | undefined;
  sizeSpecifiedByUser: boolean;
}

export interface PipelineResolvedIngredient {
  rowId: string;
  rawName: string;
  canonicalName: string;
  matchType: string;
  grams: number;
  macros?: PipelineMacros | undefined;
  source: string;
  portionKind: PortionKind;
  count?: number | undefined;
  perUnitGrams?: number | undefined;
  nutritionOrigin: NutritionOrigin;
  fdcId?: string | undefined;
  usdaDatasetVersion?: string | undefined;
  nutrientsPer100g?: PipelineMacros | undefined;
  fieldProvenance: IngredientFieldProvenance[];
}

export interface PipelineClarificationOption {
  /** stable; matcher key */
  optionId: string;
  /** user-facing copy, no grams */
  label: string;
  /** optional fine print, e.g. "≈ 35g each" */
  detail?:
    | string
    | undefined;
  /** total grams this option resolves to (count baked in) */
  grams: number;
  calorieDelta: number;
}

export interface PipelineClarification {
  /** stable; matcher key */
  clarificationId: string;
  /** links to PipelineDecomposedIngredient.row_id */
  rowId: string;
  /** display only */
  ingredientName: string;
  /** drives icon / copy variant */
  portionKind: PortionKind;
  question: string;
  options: PipelineClarificationOption[];
  defaultOptionId: string;
}

export interface PipelineStartedData {
  analysisId: string;
}

export interface PipelineDecompositionData {
  analysisId: string;
  mealName: string;
  confidence: number;
  ingredients: PipelineDecomposedIngredient[];
  inferredMealType: MealType;
  mealTypeConfident: boolean;
  interpretationOrigin: InterpretationOrigin;
  proposal?: IngredientProposalV1 | undefined;
}

export interface PipelineIngredientsData {
  analysisId: string;
  /** propagated from decomposition for cold-replay headers */
  mealName: string;
  ingredients: PipelineResolvedIngredient[];
}

export interface PipelineUncertaintyData {
  analysisId: string;
  mealName: string;
  variancePercent: number;
  needsClarification: boolean;
  calorieBand?: PipelineCalorieBand | undefined;
  clarifications: PipelineClarification[];
}

export interface PipelineMealTypeQuestionData {
  analysisId: string;
  mealName: string;
  question: string;
  options: MealType[];
  inferredMealType: MealType;
}

export interface PipelineResultData {
  analysisId: string;
  mealName: string;
  quantity: string;
  mealType: MealType;
  mealTypeSource: string;
  tip: string;
  health?: PipelineMealHealth | undefined;
  macros?: PipelineMacros | undefined;
  calorieConfidence: CalorieConfidence;
  calorieBand?: PipelineCalorieBand | undefined;
  ingredients: PipelineResolvedIngredient[];
  confidenceReasons: string[];
  receipt?: MealAnalysisReceipt | undefined;
}

export interface PipelineErrorData {
  analysisId: string;
  message: string;
  retryable: boolean;
}

export interface MealAnalysisPipelineSessionContext {
  result?: PipelineResultData | undefined;
  imageBytes?: Uint8Array | undefined;
  imageUrl?: string | undefined;
  textDescription?: string | undefined;
  isRevised: boolean;
}
