// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: protos/calorify/meal_analysis_pipeline.proto

/* eslint-disable */
import type { CalorieConfidence, HealthScore, MealType } from "../meal/meal";

export const protobufPackage = "calorify";

/** V2 NDJSON/SSE line field `step` (string on the wire matches enum value names). */
export const PipelineStep = {
  PIPELINE_STEP_UNSPECIFIED: "PIPELINE_STEP_UNSPECIFIED",
  STARTED: "STARTED",
  DECOMPOSITION: "DECOMPOSITION",
  INGREDIENTS: "INGREDIENTS",
  UNCERTAINTY: "UNCERTAINTY",
  MEAL_TYPE_QUESTION: "MEAL_TYPE_QUESTION",
  RESULT: "RESULT",
  ERROR: "ERROR",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type PipelineStep = typeof PipelineStep[keyof typeof PipelineStep];

export namespace PipelineStep {
  export type PIPELINE_STEP_UNSPECIFIED = typeof PipelineStep.PIPELINE_STEP_UNSPECIFIED;
  export type STARTED = typeof PipelineStep.STARTED;
  export type DECOMPOSITION = typeof PipelineStep.DECOMPOSITION;
  export type INGREDIENTS = typeof PipelineStep.INGREDIENTS;
  export type UNCERTAINTY = typeof PipelineStep.UNCERTAINTY;
  export type MEAL_TYPE_QUESTION = typeof PipelineStep.MEAL_TYPE_QUESTION;
  export type RESULT = typeof PipelineStep.RESULT;
  export type ERROR = typeof PipelineStep.ERROR;
  export type UNRECOGNIZED = typeof PipelineStep.UNRECOGNIZED;
}

export interface PipelineCalorieBand {
  min: number;
  max: number;
}

export interface PipelineMacros {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface PipelineMealHealth {
  healthScore: HealthScore;
  healthScoreReason: string;
}

export interface PipelineDecomposedIngredient {
  rawName: string;
  canonicalHint: string;
  gramsEstimated: number;
  minGrams: number;
  maxGrams: number;
  notes: string;
}

export interface PipelineResolvedIngredient {
  rawName: string;
  canonicalName: string;
  matchType: string;
  grams: number;
  macros?: PipelineMacros | undefined;
  source: string;
}

export interface PipelineClarificationOption {
  label: string;
  grams: number;
  calorieDelta: number;
}

export interface PipelineClarification {
  ingredientName: string;
  question: string;
  options: PipelineClarificationOption[];
  defaultOptionIndex: number;
}

export interface PipelineStartedData {
  analysisId: string;
}

export interface PipelineDecompositionData {
  analysisId: string;
  mealName: string;
  confidence: number;
  ingredients: PipelineDecomposedIngredient[];
  inferredMealType: MealType;
  mealTypeConfident: boolean;
}

export interface PipelineIngredientsData {
  analysisId: string;
  ingredients: PipelineResolvedIngredient[];
}

export interface PipelineUncertaintyData {
  analysisId: string;
  variancePercent: number;
  needsClarification: boolean;
  calorieBand?: PipelineCalorieBand | undefined;
  clarifications: PipelineClarification[];
}

export interface PipelineMealTypeQuestionData {
  analysisId: string;
  question: string;
  options: MealType[];
  inferredMealType: MealType;
}

export interface PipelineResultData {
  analysisId: string;
  mealName: string;
  quantity: string;
  mealType: MealType;
  mealTypeSource: string;
  tip: string;
  health?: PipelineMealHealth | undefined;
  macros?: PipelineMacros | undefined;
  calorieConfidence: CalorieConfidence;
  calorieBand?: PipelineCalorieBand | undefined;
  ingredients: PipelineResolvedIngredient[];
}

export interface PipelineErrorData {
  analysisId: string;
  message: string;
}

/** Session state after a successful pipeline result (client-only; shared by app + watch). */
export interface MealAnalysisPipelineSessionContext {
  result?: PipelineResultData | undefined;
  imageBytes?: Uint8Array | undefined;
  imageUrl?: string | undefined;
  textDescription?: string | undefined;
  isRevised: boolean;
}
