// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.27.3
// source: protos/calorify/meal_detection.proto

/* eslint-disable */
import type { CalorieConfidence, Meal, MealMacro } from "../meal/meal";

export const protobufPackage = "calorify";

export interface Variation {
  /** The question to ask the user (e.g., "What does the white bowl contain?") */
  question: string;
  /** List of options with their expected macros */
  options: Variation_Option[];
}

export interface Variation_Option {
  /** The option text (e.g., "curd", "labaan") */
  option: string;
  /** Expected macros diff if this option is selected */
  macroDiff?: MealMacro | undefined;
}

export interface MealMetadata {
  imageUrl?: string | undefined;
  mealDescription?: string | undefined;
  selectedVariations: Variation[];
}

export interface MealDetectionResult {
  mealIdentified: boolean;
  calorieConfidence: CalorieConfidence;
  tip: string;
  meal?: Meal | undefined;
  metadata?: MealMetadata | undefined;
}

export interface ImageMealDetectionRequest {
  imageUrl: string;
  mimeType?: string | undefined;
}

export interface TextMealDetectionRequest {
  textDescription: string;
}

export interface MealDetectionResponse {
  result?: MealDetectionResult | undefined;
  variations: Variation[];
}
