// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.27.3
// source: protos/calorify/meal_analysis_pipeline.proto

/* eslint-disable */
import type { CalorieConfidence, HealthScore, MealType } from "../meal/meal";

export const protobufPackage = "calorify";

export const PipelineStep = {
  PIPELINE_STEP_UNSPECIFIED: "PIPELINE_STEP_UNSPECIFIED",
  STARTED: "STARTED",
  DECOMPOSITION: "DECOMPOSITION",
  INGREDIENTS: "INGREDIENTS",
  UNCERTAINTY: "UNCERTAINTY",
  MEAL_TYPE_QUESTION: "MEAL_TYPE_QUESTION",
  RESULT: "RESULT",
  ERROR: "ERROR",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type PipelineStep = typeof PipelineStep[keyof typeof PipelineStep];

export namespace PipelineStep {
  export type PIPELINE_STEP_UNSPECIFIED = typeof PipelineStep.PIPELINE_STEP_UNSPECIFIED;
  export type STARTED = typeof PipelineStep.STARTED;
  export type DECOMPOSITION = typeof PipelineStep.DECOMPOSITION;
  export type INGREDIENTS = typeof PipelineStep.INGREDIENTS;
  export type UNCERTAINTY = typeof PipelineStep.UNCERTAINTY;
  export type MEAL_TYPE_QUESTION = typeof PipelineStep.MEAL_TYPE_QUESTION;
  export type RESULT = typeof PipelineStep.RESULT;
  export type ERROR = typeof PipelineStep.ERROR;
  export type UNRECOGNIZED = typeof PipelineStep.UNRECOGNIZED;
}

export const PortionKind = {
  PORTION_KIND_UNSPECIFIED: "PORTION_KIND_UNSPECIFIED",
  /** COUNT - discrete units: roti, slice, egg, piece */
  COUNT: "COUNT",
  /** BULK - spoon/cup/bowl foods: rice, dal, sabzi, sauces */
  BULK: "BULK",
  /** PINCH - trace amounts: salt, spices, garnishes */
  PINCH: "PINCH",
  /** COUNT_QUESTION - synthetic; clarification asks "how many?" */
  COUNT_QUESTION: "COUNT_QUESTION",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type PortionKind = typeof PortionKind[keyof typeof PortionKind];

export namespace PortionKind {
  export type PORTION_KIND_UNSPECIFIED = typeof PortionKind.PORTION_KIND_UNSPECIFIED;
  export type COUNT = typeof PortionKind.COUNT;
  export type BULK = typeof PortionKind.BULK;
  export type PINCH = typeof PortionKind.PINCH;
  export type COUNT_QUESTION = typeof PortionKind.COUNT_QUESTION;
  export type UNRECOGNIZED = typeof PortionKind.UNRECOGNIZED;
}

export interface PipelineCalorieBand {
  min: number;
  max: number;
}

export interface PipelineMacros {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface PipelineMealHealth {
  healthScore: HealthScore;
  healthScoreReason: string;
}

export interface PipelineDecomposedIngredient {
  /** stable id per row; survives clarify replays */
  rowId: string;
  rawName: string;
  canonicalHint: string;
  /**
   * Total grams used downstream for macro math. Server enforces:
   *   if portion_kind == COUNT: grams_estimated = count * per_unit_grams
   */
  gramsEstimated: number;
  minGrams: number;
  maxGrams: number;
  notes: string;
  portionKind: PortionKind;
  /** fractional ok; null if not extracted */
  count?: number | undefined;
  perUnitGrams?: number | undefined;
  perUnitMinGrams?: number | undefined;
  perUnitMaxGrams?: number | undefined;
  sizeSpecifiedByUser: boolean;
}

export interface PipelineResolvedIngredient {
  rowId: string;
  rawName: string;
  canonicalName: string;
  matchType: string;
  grams: number;
  macros?: PipelineMacros | undefined;
  source: string;
  portionKind: PortionKind;
  count?: number | undefined;
  perUnitGrams?: number | undefined;
}

export interface PipelineClarificationOption {
  /** stable; matcher key */
  optionId: string;
  /** user-facing copy, no grams */
  label: string;
  /** optional fine print, e.g. "≈ 35g each" */
  detail?:
    | string
    | undefined;
  /** total grams this option resolves to (count baked in) */
  grams: number;
  calorieDelta: number;
}

export interface PipelineClarification {
  /** stable; matcher key */
  clarificationId: string;
  /** links to PipelineDecomposedIngredient.row_id */
  rowId: string;
  /** display only */
  ingredientName: string;
  /** drives icon / copy variant */
  portionKind: PortionKind;
  question: string;
  options: PipelineClarificationOption[];
  defaultOptionId: string;
}

export interface PipelineStartedData {
  analysisId: string;
}

export interface PipelineDecompositionData {
  analysisId: string;
  mealName: string;
  confidence: number;
  ingredients: PipelineDecomposedIngredient[];
  inferredMealType: MealType;
  mealTypeConfident: boolean;
}

export interface PipelineIngredientsData {
  analysisId: string;
  /** propagated from decomposition for cold-replay headers */
  mealName: string;
  ingredients: PipelineResolvedIngredient[];
}

export interface PipelineUncertaintyData {
  analysisId: string;
  mealName: string;
  variancePercent: number;
  needsClarification: boolean;
  calorieBand?: PipelineCalorieBand | undefined;
  clarifications: PipelineClarification[];
}

export interface PipelineMealTypeQuestionData {
  analysisId: string;
  mealName: string;
  question: string;
  options: MealType[];
  inferredMealType: MealType;
}

export interface PipelineResultData {
  analysisId: string;
  mealName: string;
  quantity: string;
  mealType: MealType;
  mealTypeSource: string;
  tip: string;
  health?: PipelineMealHealth | undefined;
  macros?: PipelineMacros | undefined;
  calorieConfidence: CalorieConfidence;
  calorieBand?: PipelineCalorieBand | undefined;
  ingredients: PipelineResolvedIngredient[];
  confidenceReasons: string[];
}

export interface PipelineErrorData {
  analysisId: string;
  message: string;
  retryable: boolean;
}

export interface MealAnalysisPipelineSessionContext {
  result?: PipelineResultData | undefined;
  imageBytes?: Uint8Array | undefined;
  imageUrl?: string | undefined;
  textDescription?: string | undefined;
  isRevised: boolean;
}
