// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v7.34.1
// source: protos/app/meal.proto

/* eslint-disable */
import type { MealMetadata } from "../calorify/meal_detection";
import type { Meal } from "../meal/meal";

export const protobufPackage = "app";

export interface LoggedMeal {
  clientId: number;
  meal?: Meal | undefined;
  createdAt: string;
  metadata?: MealMetadata | undefined;
}

export interface FavoriteMeal {
  clientId: number;
  loggedMeal?: LoggedMeal | undefined;
  favoriteAt: string;
  lastUsedAt: string;
}
