// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: protos/app/sync.proto

/* eslint-disable */
import type { FcmToken } from "../calorify/common";
import type { UserProfile } from "../user/user";
import type { LoggedMeal } from "./meal";

export const protobufPackage = "app";

export const SyncOpType = {
  SYNC_OP_TYPE_UNSPECIFIED: "SYNC_OP_TYPE_UNSPECIFIED",
  SYNC_OP_TYPE_UPSERT_MEAL: "SYNC_OP_TYPE_UPSERT_MEAL",
  SYNC_OP_TYPE_DELETE_MEAL: "SYNC_OP_TYPE_DELETE_MEAL",
  SYNC_OP_TYPE_UPSERT_PROFILE: "SYNC_OP_TYPE_UPSERT_PROFILE",
  SYNC_OP_TYPE_FCM_TOKEN: "SYNC_OP_TYPE_FCM_TOKEN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type SyncOpType = typeof SyncOpType[keyof typeof SyncOpType];

export namespace SyncOpType {
  export type SYNC_OP_TYPE_UNSPECIFIED = typeof SyncOpType.SYNC_OP_TYPE_UNSPECIFIED;
  export type SYNC_OP_TYPE_UPSERT_MEAL = typeof SyncOpType.SYNC_OP_TYPE_UPSERT_MEAL;
  export type SYNC_OP_TYPE_DELETE_MEAL = typeof SyncOpType.SYNC_OP_TYPE_DELETE_MEAL;
  export type SYNC_OP_TYPE_UPSERT_PROFILE = typeof SyncOpType.SYNC_OP_TYPE_UPSERT_PROFILE;
  export type SYNC_OP_TYPE_FCM_TOKEN = typeof SyncOpType.SYNC_OP_TYPE_FCM_TOKEN;
  export type UNRECOGNIZED = typeof SyncOpType.UNRECOGNIZED;
}

export interface DeleteMeal {
  clientId: string;
  localId: number;
}

export interface SyncOp {
  idempotencyKey: string;
  opType: SyncOpType;
  createdAt: string;
  meal?: LoggedMeal | undefined;
  deleteMeal?: DeleteMeal | undefined;
  profile?: UserProfile | undefined;
  fcmToken?: FcmToken | undefined;
}

export interface SyncBatch {
  ops: SyncOp[];
}

export interface SyncResult {
  idempotencyKey: string;
  success: boolean;
  error: string;
  remoteId: string;
}

export interface SyncAck {
  results: SyncResult[];
}
