enum AnalyticsEvent {
  // Onboarding
  onboardingStart,
  onboardingSetWeightGoal,
  onboardingSetActivityLevel,
  onboardingGoalLifestyleComplete,
  onboardingSetGender,
  onboardingSetHeight,
  onboardingSetWeight,
  onboardingHealthProfileComplete,
  onboardingSetTargetWeight,
  onboardingSetAge,
  onboardingTrackingSuccessComplete,
  onboardingSetupHealthConnect,
  onboardingSkipHealthConnect,
  onboardingContinueHealthConnect,
  onboardingEnableNotifications,
  onboardingSetReminders,
  onboardingSkipReminders,
  onboardingComplete,

  // Home
  homeView,
  viewDashboard,
  viewLog,
  viewHistory,
  viewFavorites,
  setDailyGoal,
  connectHealth,
  addMealFromFavorites,
  addMealFromDescription,

  // Meal
  mealSnapFromCamera,
  mealSnapFromGallery,
  mealSave,
  mealDelete,
  mealEdit,
  mealQuestionFlowShown,
  mealQuestionFlowNext,
  mealQuestionFlowSkip,
  mealQuestionFlowBack,
  mealQuestionFlowComplete,
  mealQuestionFlowDismissed,
  mealDetectionSuccess,
  mealDetectionFailure,
  mealAnalysisV2Started,
  mealAnalysisV2Completed,
  mealAnalysisV2Failed,
  mealQuestionFlowContinue,
  mealTypeQuestionShown,
  mealTypeQuestionAnswered,
  mealTypeQuestionDismissed,
  mealFeedbackShown,
  mealFeedbackThumbsUp,
  mealFeedbackThumbsDownOpened,
  mealFeedbackThumbsDownSubmitted,
  mealReanalysisSucceeded,
  mealReanalysisFailed,

  // Favorites
  favoriteAdd,
  favoriteRemove,

  // Health Connect
  healthConnectPermissionGranted,
  healthConnectPermissionDenied,

  // Misc
  easterEggDiscovered,

  // Feedback / rating sheet
  feedbackSheetShown,
  feedbackSheetEnjoyingYes,
  feedbackSheetEnjoyingNo,
  feedbackSheetRateYes,
  feedbackSheetRateNo,
  feedbackSheetEmailYes,
  feedbackSheetEmailNo,
  feedbackSheetDismissed,
}
