ALTER TABLE usda_foods
  ADD COLUMN IF NOT EXISTS kcal_present BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS protein_present BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS carbs_present BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS fat_present BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS fiber_present BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE usda_dataset_version
  ADD COLUMN IF NOT EXISTS v3_nutrient_presence_materialized BOOLEAN NOT NULL DEFAULT FALSE;
