name: models
description: Shared models for Calorify app and watch companion
version: 1.2.1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  protobuf: ^4.0.0
  health: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  protoc_plugin: ^22.5.0
