name: models
description: Shared models for Calorify app and watch companion
version: 1.2.1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  protobuf: ^5.1.0
  fixnum: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  protoc_plugin: 24.0.0
