library i18n;

// Export generated strings - these will be generated by slang
// Run: dart run slang
// This exports all generated types including:
// - LocaleSettings
// - TranslationProvider
// - AppLocale
// - AppLocaleUtils
// - Translations
// - All locale-specific translation classes
export 'i18n/strings.g.dart';
