name: services
description: Shared services for Calorify app and watch companion
version: 1.2.1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flashy_flushbar: ^1.4.1
  models:
    path: ../models
  i18n:
    path: ../i18n
  firebase_auth: ^6.1.0
  device_info_plus: ^12.1.0
  url_launcher: ^6.3.2
  in_app_review: ^2.0.9
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
