name: calorify_watch
description: Calorify companion watch app
version: 1.2.16+48
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Shared packages
  specs:
    path: ../shared_packages/specs
  models:
    path: ../shared_packages/models
  widgets:
    path: ../shared_packages/widgets
  i18n:
    path: ../shared_packages/i18n
  flutter_localizations:
    sdk: flutter
  
  speech_to_text: ^7.0.0
  
  # UI
  auto_route: ^11.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  speech_to_text_platform_interface: ^2.3.0

flutter:
  uses-material-design: true
