name: Flutter Android CI/CD

on:
  push:
    tags:
    - 'v.*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate tag format
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ ! $TAG_NAME =~ ^v\.[0-9]+\.[0-9]+\.[0-9]+\+[0-9]+$ ]]; then
            echo "Error: Tag $TAG_NAME does not match pattern v.x.x.x+number"
            exit 1
          fi
          echo "Tag $TAG_NAME is valid"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5" # adjust to your version

      - name: Install dependencies
        run: bash scripts/flutter_pub_get_all.sh

      - name: Decode Android signing files
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 --decode > app/android/app/upload-keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES_B64 }}" | base64 --decode > app/android/key.properties
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 --decode > watch_app/android/app/upload-keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES_B64 }}" | base64 --decode > watch_app/android/key.properties

      - name: Build Android AppBundle (Main App)
        working-directory: app
        run: flutter build appbundle --release --flavor=prod

      # - name: Build Android AppBundle (Watch App)
      #   working-directory: watch_app
      #   run: flutter build appbundle --release

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"

      - name: Install Fastlane
        run: gem install fastlane

      - name: Upload to Play Store
        run: fastlane android release
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
      
