name: Flutter Android CI/CD

on:
  push:
    branches:
    - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5" # adjust to your version

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Decode Android signing files
        working-directory: app/android
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 --decode > app/upload-keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES_B64 }}" | base64 --decode > key.properties

      - name: Build Android AppBundle
        working-directory: app
        run: flutter build appbundle --release --flavor=prod

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"

      - name: Install Fastlane
        run: gem install fastlane

      - name: Upload to Play Store
        working-directory: app
        run: fastlane android release
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
      
