name: Flutter Watch App Release

on:
  workflow_dispatch:

jobs:
  release-android-watch-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"
          bundler-cache: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare Android SDK build-cache for caching
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/build-cache
          sudo chmod -R 777 /usr/local/lib/android/sdk/build-cache

      - name: Cache Android SDK build-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/build-cache
          key: ${{ runner.os }}-android-sdk-build-cache
          restore-keys: |
            ${{ runner.os }}-android-sdk-build-cache-

      - name: Decode Android signing files
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 --decode > watch_app/android/app/upload-keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES_B64 }}" | base64 --decode > watch_app/android/key.properties

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.0"
          channel: stable
          cache: true

      - name: Install dependencies
        working-directory: watch_app
        run: flutter pub get

      - name: Build Android AppBundle (Watch App)
        working-directory: watch_app
        run: flutter build appbundle --release

      - name: Install Ruby dependencies
        run: bundle install

      - name: Upload Watch App to Play Store
        run: bundle exec fastlane android release_watch
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
